name: update guangying nodes

on:
  schedule:
    - cron: '0 */12 * * *'   # 每12小时执行一次
  workflow_dispatch:         # 手动触发也可以

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: gy-hunter

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y masscan nmap curl git

      - name: Run guangying.py
        run: |
          python3 -m pip install --upgrade pip
          cd gy-hunter
          python3 guangying.py
