name: Auto Update Glider Sub

on:
  schedule:
    - cron: '0 */6 * * *' # 每 6 小时自动运行一次
  workflow_dispatch: # 支持手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography requests

      - name: Run script
        run: |
          python 滑翔伞.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add 滑翔伞.txt
          git commit -m "Auto update and filter subscription" || exit 0
          git push
