name: Update Yingmao Subscriptions

on:
  schedule:
    - cron: '0 */11  * * *' # 每 11 小時自動運行一次
  workflow_dispatch: # 支援在 GitHub 網頁手動點擊觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests pyaes

      - name: Run Yingmao script
        run: |
          python3 "影猫.py"

      - name: Commit and Push update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 這裡預設將腳本輸出的檔案（nodes.txt 和 subscribe.txt）加入
          git add nodes.txt subscribe.txt || exit 0
          git commit -m "Auto update yingmao nodes [skip ci]" || exit 0
          git push
